ruby_version: 2.5.0
fix: true
parallel: true
ignore:
  - test/**/*
  - examples/**/*
  - myapp/**/*
  - 'lib/faktory.rb':
    - Lint/InheritException
  - 'lib/**/*':
    - Lint/RescueException
    - Style/GlobalVars
